version: "3"
services:
  db:
    image: postgres:11.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uma
  adminer:
    image: adminer
    ports:
      - 8080:8080
