# Generated by Django 2.2.3 on 2019-07-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0001_squashed_0012_holiday_day_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
