# Generated by Django 2.2.3 on 2019-07-29 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0001_squashed_0006_auto_20190728_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='uma.RoomCategory'),
        ),
        migrations.AlterField(
            model_name='room',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='uma.RoomMode'),
        ),
    ]
