# Generated by Django 2.2.3 on 2019-07-28 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0001_squashed_0005_room_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='uma.RoomCategory'),
        ),
        migrations.AlterField(
            model_name='room',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='uma.RoomMode'),
        ),
    ]
