# Generated by Django 2.2.3 on 2019-07-28 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0002_auto_20190728_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uma.RoomCategory')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uma.Stay')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
