# Generated by Django 2.2.3 on 2019-07-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0003_noneditablestayrate_stay_stayrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stayrate',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='uma.RoomCategory'),
        ),
    ]
