# Generated by Django 2.2.3 on 2019-07-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0004_article_articlecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name_plural': 'article categories'},
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, upload_to='articles'),
        ),
    ]
