# Generated by Django 2.2.3 on 2019-07-26 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0004_stayrate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='uma.RoomMode'),
        ),
    ]
