# Generated by Django 2.2.3 on 2019-07-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0004_roomcategory_stays'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlecomponent',
            unique_together={('parent', 'child')},
        ),
    ]
