# Generated by Django 2.2.3 on 2019-07-21 22:50

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0007_articleprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articleprice',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('ARS', 'Argentine Peso')], default='ARS', editable=False, max_length=3),
        ),
    ]
