# Generated by Django 2.2.3 on 2019-07-24 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0009_auto_20190723_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_article_components', to='uma.Article')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_article_components', to='uma.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='components',
            field=models.ManyToManyField(through='uma.ArticleComponent', to='uma.Article'),
        ),
    ]
