# Generated by Django 2.2.3 on 2019-07-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0010_auto_20190724_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
