# Generated by Django 2.2.3 on 2019-07-25 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0011_daytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='day_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uma.DayType'),
        ),
    ]
